package net.crulim.luckblockcobblemon.util;

import net.crulim.luckblockcobblemon.config.LuckyBlockConfigManager;

import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public class ReadmeGenerator {

    public static void generateReadmeIfMissing() {
        LuckyBlockConfigManager.ensureDirectories();

        Path readme = LuckyBlockConfigManager.rootDir().resolve("README.txt");
        if (Files.exists(readme)) {
            return;
        }

        String content = """
                ==============================
                LUCKY BLOCK COBBLEMON CONFIGS
                ==============================

                Official config folder:

                config/luckyblockcobblemon/
                ├── settings.json
                ├── tiers.json
                └── pools/
                    ├── default.json
                    ├── legendary.json
                    └── themed/
                        ├── fire.json
                        ├── water.json
                        ├── grass.json
                        ├── ground.json
                        ├── fly.json
                        ├── steel.json
                        ├── eletric.json
                        └── fairy.json

                IMPORTANT:

                The files generated by the mod are GLOBAL public defaults.
                If you want a custom server experience, edit or replace the files in this folder.

                Main files:

                settings.json
                - Enables/disables recipes, worldgen, structure events, strict mode and Creative Mode behavior.
                - enableStructureWorldgen controls natural structure generation in new chunks.
                - enableStructureEvents controls whether Lucky Block pool events of type structure are allowed to run.
                - strictConfigEvents prevents hidden fallback events outside the loaded config.

                tiers.json
                - Controls locked-tier level ranges used by:
                  /luckyblockgive <target> <type> <tier> [amount]

                pools/default.json
                - Controls the regular/default Lucky Block events.
                - This file uses the events array.
                - The default generated file keeps the same event types and chances from the legacy default config.

                pools/legendary.json
                - Controls the Legendary Lucky Block species, level ranges and shiny chance.

                pools/themed/*.json
                - Controls each themed Lucky Block.
                - The pokemon/pokemons list controls exactly which species can spawn.
                - The default generated files keep the same event types, species lists and chances from the legacy themed configs.

                Commands:

                /luckyblock reload
                - Reloads Lucky Block configs.
                - Requires admin/operator permission.

                /luckyblockgive <target> <type> <tier> [amount]
                - Gives locked-tier Lucky Blocks.
                - Types: default, fire, water, grass, ground, fly, steel, eletric, fairy.
                - Default aliases: default, normal, base, pocket.
                - Requires admin/operator permission.

                /luckyblocklocate [range]
                - Finds Lucky Blocks in loaded chunks.
                - Requires admin/operator permission.

                Legacy compatibility:

                Older config files are still supported when the new files do not exist yet.
                On first load, the mod can migrate old files into the new folder.
                Once the new folder exists and has been customized, it takes priority.

                Legacy files kept for compatibility:
                - config/luckyblock_settings.json
                - config/luckyblock_locked_tiers.json
                - config/luckyblock_config.json
                - config/luckyblock_legendary.json
                - config/luckblockpocket/*.json

                Server safety:

                The mod no longer runs hidden fallback events when a pool is empty or when all chances are 0.
                If a valid event is not present in the loaded config, it will not run.
                Structure events require both:
                - an explicit structure event inside the pool
                - enableStructureEvents: true in settings.json
                """;

        try (Writer writer = new OutputStreamWriter(Files.newOutputStream(readme), StandardCharsets.UTF_8)) {
            writer.write(content);
            System.out.println("[LuckyBlockCobblemon] Generated config/luckyblockcobblemon/README.txt");
        } catch (IOException e) {
            System.out.println("[LuckyBlockCobblemon] Failed to generate config README: " + e.getMessage());
        }
    }
}
